# Generated by Django 5.1.3 on 2025-01-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw_app', '0002_remove_quiz_is_active_quiz_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.TextField(blank=True, null=True),
        ),
    ]
