# Generated by Django 5.1.3 on 2025-01-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw_app', '0003_alter_choice_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='selected_choice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='is_correct',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
