# Generated by Django 5.1.3 on 2025-01-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw_app', '0004_alter_useranswer_selected_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
